In [1]:
import numpy as np

In [7]:
numbers = np.arange(1,6)

In [4]:
numbers*2

array([ 2,  4,  6,  8, 10])

In [9]:
numbers

array([1, 2, 3, 4, 5])

In [10]:
numbers += 10

In [11]:
numbers2 = np.linspace(1.1,5.5,5)

In [12]:
numbers*numbers2

array([12.1, 26.4, 42.9, 61.6, 82.5])

In [13]:
numbers <= 13

array([ True,  True,  True, False, False])

In [14]:
numbers == numbers2

array([False, False, False, False, False])