In [1]:
import numpy as np

In [2]:
numbers = np.arange(1,6)
numbers

array([1, 2, 3, 4, 5])

In [3]:
numbers2 = numbers.copy()
numbers2

array([1, 2, 3, 4, 5])

In [4]:
numbers*=10

In [6]:
numbers

array([10, 20, 30, 40, 50])

In [7]:
numbers2

array([1, 2, 3, 4, 5])