In [1]:
import numpy as np

In [9]:
grades = np.array([[87,98,56],[78,86,85]])
grades

array([[87, 98, 56],
       [78, 86, 85]])

In [7]:
grades.reshape(1,6)

array([[87, 98, 56, 78, 86, 85]])

In [8]:
grades.resize(1,6)
grades

array([[87, 98, 56, 78, 86, 85]])

In [11]:
flattened = grades.flatten()

In [12]:
flattened

array([87, 98, 56, 78, 86, 85])

In [13]:
raveled = grades.ravel()

In [14]:
raveled

array([87, 98, 56, 78, 86, 85])

In [15]:
grades.T

array([[87, 78],
       [98, 86],
       [56, 85]])

In [16]:
grades2 = np.array([[87,98,56],[78,86,85]])

In [17]:
np.hstack((grades,grades2))

array([[87, 98, 56, 87, 98, 56],
       [78, 86, 85, 78, 86, 85]])

In [18]:
np.vstack((grades,grades2))

array([[87, 98, 56],
       [78, 86, 85],
       [87, 98, 56],
       [78, 86, 85]])