In [2]:
import numpy as np

In [17]:
grades = np.array([[87,98,56],[78,86,85]])
grades

array([[87, 98, 56],
       [78, 86, 85]])

In [4]:
grades.reshape(1,6)                 #Returns a view

array([[87, 98, 56, 78, 86, 85]])

In [5]:
grades.resize(1,6)                  #Returns a view and it modifies the original array's shape
grades

array([[87, 98, 56, 78, 86, 85]])

In [14]:
flattened = grades.flatten()        #Deep copies the original array's data

In [15]:
flattened

array([87, 98, 56, 78, 86, 85])

In [16]:
grades

array([[87, 98, 56],
       [78, 86, 85]])

In [8]:
raveled = grades.ravel()            #It produces a view of the original array

In [9]:
raveled

array([87, 98, 56, 78, 86, 85])

In [18]:
grades.T                #Returns a transposed view of the array

array([[87, 78],
       [98, 86],
       [56, 85]])

In [19]:
grades

array([[87, 98, 56],
       [78, 86, 85]])

In [20]:
grades2 = np.array([[87,98,56],[78,86,85]])
grades2

array([[87, 98, 56],
       [78, 86, 85]])

In [21]:
np.hstack((grades,grades2))

array([[87, 98, 56, 87, 98, 56],
       [78, 86, 85, 78, 86, 85]])

In [18]:
np.vstack((grades,grades2))

array([[87, 98, 56],
       [78, 86, 85],
       [87, 98, 56],
       [78, 86, 85]])