In [5]:
import numpy as np

In [6]:
grades = np.array([[87,96,70],[77,78,89]])
grades

array([[87, 96, 70],
       [77, 78, 89]])

In [7]:
grades.dtype

dtype('int64')

In [8]:
grades.sum()

np.int64(497)

In [9]:
grades.min()

np.int64(70)

In [10]:
grades.max()

np.int64(96)

In [11]:
grades.mean()

np.float64(82.83333333333333)

In [12]:
grades.std()

np.float64(8.668269082630562)

In [13]:
grades.var()

np.float64(75.13888888888889)

In [14]:
grades.mean(axis=0)

array([82. , 87. , 79.5])

In [15]:
grades.mean(axis=1)

array([84.33333333, 81.33333333])