In [50]:
import numpy as np

In [51]:
numbers = np.arange(1,6)
numbers

array([1, 2, 3, 4, 5])

In [52]:
numbers2 = numbers.view()
numbers2

array([1, 2, 3, 4, 5])

In [53]:
id(numbers)

1897481196080

In [54]:
id(numbers2)        #numbers2 and numbers are different objects, but share data

1897481195024

In [55]:
numbers[1]*=10
numbers

array([ 1, 20,  3,  4,  5])

In [56]:
numbers2

array([ 1, 20,  3,  4,  5])

In [57]:
numbers2[1]/=10
numbers2

array([1, 2, 3, 4, 5])

In [58]:
numbers

array([1, 2, 3, 4, 5])

In [59]:
numbers2 = numbers[0:3]
numbers2

array([1, 2, 3])

In [60]:
numbers[1]*=20

In [61]:
numbers

array([ 1, 40,  3,  4,  5])

In [62]:
numbers2

array([ 1, 40,  3])

In [63]:
id(numbers)

1897481196080

In [64]:
id(numbers2)

1897481196464