In [1]:
import numpy as np

In [2]:
grades = np.array([[87,98,56],[78,86,85]])
grades

array([[87, 98, 56],
       [78, 86, 85]])

In [3]:
grades.reshape(1,6)

array([[87, 98, 56, 78, 86, 85]])

In [4]:
grades.resize(1,6)
grades

array([[87, 98, 56, 78, 86, 85]])

In [5]:
flattened = grades.flatten()

In [6]:
flattened

array([87, 98, 56, 78, 86, 85])

In [7]:
raveled = grades.ravel()

In [8]:
raveled

array([87, 98, 56, 78, 86, 85])

In [9]:
grades.T

array([[87],
       [98],
       [56],
       [78],
       [86],
       [85]])

In [10]:
grades2 = np.array([[87,98,56],[78,86,85]])

In [11]:
np.hstack((grades,grades2))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 1 and the array at index 1 has size 2

In [18]:
np.vstack((grades,grades2))

array([[87, 98, 56],
       [78, 86, 85],
       [87, 98, 56],
       [78, 86, 85]])