In [1]:
import numpy as np

In [2]:
numbers = np.arange(1,6)

In [3]:
numbers2 = numbers.view()

In [4]:
numbers

array([1, 2, 3, 4, 5])

In [5]:
numbers2

array([1, 2, 3, 4, 5])

In [6]:
numbers[1]*=10

In [7]:
numbers

array([ 1, 20,  3,  4,  5])

In [8]:
numbers2

array([ 1, 20,  3,  4,  5])

In [9]:
numbers2[1]/=10
numbers

array([1, 2, 3, 4, 5])

In [10]:
numbers2 = numbers[0:3]
numbers2

array([1, 2, 3])

In [11]:
numbers[1]*=20

In [12]:
numbers

array([ 1, 40,  3,  4,  5])

In [13]:
numbers2

array([ 1, 40,  3])