In [1]:
import numpy as np

In [2]:
grades = np.array([[87,96,70],[100,87,90],[94,74,75],[100,81,82]])

In [3]:
grades[0,1]

np.int64(96)

In [4]:
grades[1]

array([100,  87,  90])

In [5]:
grades[0:2]

array([[ 87,  96,  70],
       [100,  87,  90]])

In [6]:
grades[[1,3]]

array([[100,  87,  90],
       [100,  81,  82]])

In [7]:
grades[:,0]

array([ 87, 100,  94, 100])

In [8]:
grades[:,1:3]

array([[96, 70],
       [87, 90],
       [74, 75],
       [81, 82]])

In [9]:
grades[:,[0,2]]

array([[ 87,  70],
       [100,  90],
       [ 94,  75],
       [100,  82]])