In [2]:
import numpy as np

In [3]:
grades = np.array([[87,96,70],[77,78,89], [95,77,90],[100,81,87]])
grades

array([[ 87,  96,  70],
       [ 77,  78,  89],
       [ 95,  77,  90],
       [100,  81,  87]])

In [4]:
grades.dtype

dtype('int64')

In [5]:
grades.sum()

np.int64(1027)

In [6]:
grades.min()

np.int64(70)

In [7]:
grades.max()

np.int64(100)

In [8]:
grades.mean()

np.float64(85.58333333333333)

In [9]:
grades.std()

np.float64(8.703048635711257)

In [10]:
grades.var()

np.float64(75.74305555555556)

In [11]:
grades.mean(axis=0)             #Calculation on all the row values within each column

array([89.75, 83.  , 84.  ])

In [12]:
grades.mean(axis=1)             #Calculation on all the column values within each individual row

array([84.33333333, 81.33333333, 87.33333333, 89.33333333])