In [1]:
import numpy as np

In [11]:
numbers = np.arange(1,6)
numbers

array([1, 2, 3, 4, 5])

In [3]:
numbers*2

array([ 2,  4,  6,  8, 10])

In [12]:
numbers ** 3

array([  1,   8,  27,  64, 125])

In [4]:
numbers             #Numbers is unchanged by the arithmetic operators

array([1, 2, 3, 4, 5])

In [5]:
numbers += 10           #Augmented assignments modify every element in the left operand

In [6]:
numbers

array([11, 12, 13, 14, 15])

In [7]:
numbers2 = np.linspace(1.1,5.5,5)

In [8]:
numbers*numbers2                #Both arrays have the same shape

array([12.1, 26.4, 42.9, 61.6, 82.5])

In [13]:
numbers

array([1, 2, 3, 4, 5])

In [15]:
(numbers >= 13)

array([False, False, False, False, False])

In [16]:
numbers2 < numbers

array([False, False, False, False, False])

In [17]:
numbers == numbers2

array([False, False, False, False, False])

In [18]:
numbers == numbers

array([ True,  True,  True,  True,  True])